In [5]:
#Numpy is a math library for python. It enables us to do computation efficiently and effectively

# Imports NumPy as np. The variable np acts a reference to the NumPy module
import numpy as np



# Lets practice the methods available in the numpy

### 1. Method Numpy array

In [ ]:
#Python array
arr = [1,2,3,4,5]

#numpy array
numpy_arr = np.array(arr)

print(arr)
print(numpy_arr)
#############################################

### 2. Method Numpy arange

In [15]:
# 2. Method Numpy arange


np.arange(1,20,1)



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [16]:
np.arange(20,1,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2])

In [19]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

### 3. Usage of Shape and Reshape of an array

In [41]:

A = [1,2,3,4,5,6]
print(A)
A = np.array(A)

[1, 2, 3, 4, 5, 6]


In [42]:
print(A)

[1 2 3 4 5 6]


In [43]:
A.shape
A.reshape(2,3)


array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
#Declare an array from 1 to 100
B = np.arange(1,101,1)
B.shape

(100,)

In [58]:
C= B.reshape(10,10)
print(B,'\n' ,C)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100] 
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


### 4. Define zeros using numpy

In [59]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 5. Define Identity matrix using eye method

In [63]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 6. Matrix Multiplication using the dot product

In [81]:
A = np.arange(1,10,1).reshape(3,3)
B = np.arange(11,20,1).reshape(3,3)
print("A=",A)
print("Order of Matrix A",A.shape)
print("B=",B)
print("Order of Matrix B",B.shape)

A= [[1 2 3]
 [4 5 6]
 [7 8 9]]
Order of Matrix A (3, 3)
B= [[11 12 13]
 [14 15 16]
 [17 18 19]]
Order of Matrix B (3, 3)


In [83]:
A_dot_B=np.dot(A,B)
print(A_dot_B)
print("Order of matrix A_dot_B",A_dot_B.shape)

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
Order of matrix A_dot_B (3, 3)


In [84]:
A = np.arange(1,9,1).reshape(2,4)
B = np.arange(11,19,1).reshape(4,2)
print("A=",A)
print("Order of Matrix A",A.shape)
print("B=",B)
print("Order of Matrix B",B.shape)

A= [[1 2 3 4]
 [5 6 7 8]]
Order of Matrix A (2, 4)
B= [[11 12]
 [13 14]
 [15 16]
 [17 18]]
Order of Matrix B (4, 2)


In [85]:
A_dot_B=np.dot(A,B)
A_dot_B=np.dot(A,B)
print(A_dot_B)
print("Order of matrix A_dot_B",A_dot_B.shape)

[[150 160]
 [374 400]]
Order of matrix A_dot_B (2, 2)


### 7.Addition of elements of the Matrix

In [88]:
M = np.arange(0,100,5).reshape(4,5)
print(M)

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]


In [89]:
# sum of the matrix M
np.sum(M)

950

In [90]:
# sum of the corresponding rows of the matrix M
np.sum(M,axis=1)

array([ 50, 175, 300, 425])

In [91]:
# sum of the corresponding columns of the matrix M
np.sum(M,axis=0)

array([150, 170, 190, 210, 230])

### 8.Generation of random values

In [94]:
np.random.rand(5,5)

array([[0.39662624, 0.44197007, 0.89963925, 0.36688751, 0.22278905],
       [0.78683603, 0.3446167 , 0.68939527, 0.95149021, 0.59900668],
       [0.63414681, 0.37968538, 0.7934025 , 0.62220137, 0.25375312],
       [0.79855727, 0.15608206, 0.2584378 , 0.95138365, 0.13108921],
       [0.53616203, 0.87393721, 0.14836097, 0.57126797, 0.48708445]])

In [96]:
np.random.rand(5,10)

array([[0.70477921, 0.9701307 , 0.79906988, 0.78055076, 0.48528767,
        0.08841311, 0.51948255, 0.46333248, 0.2958159 , 0.57934974],
       [0.61912581, 0.1515271 , 0.24470827, 0.75077806, 0.23084181,
        0.66076031, 0.45535272, 0.53372472, 0.76562799, 0.19738003],
       [0.56579162, 0.6208966 , 0.86912773, 0.86092017, 0.6277618 ,
        0.37390985, 0.5372814 , 0.67844703, 0.1604741 , 0.93618448],
       [0.76224671, 0.8676025 , 0.17961453, 0.95300961, 0.09474742,
        0.73923857, 0.08369264, 0.62337109, 0.96033546, 0.88211714],
       [0.08277493, 0.84144599, 0.88915443, 0.81553599, 0.12774771,
        0.27789391, 0.80034387, 0.22737374, 0.63753769, 0.2520794 ]])

### 9.Append of new elements to the matrix

In [99]:
# appends the element 100 to the matrix A
A = np.arange(1,11,1)
print(A)
B=np.append(A,100)
print(B)

[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3   4   5   6   7   8   9  10 100]


In [101]:
# appends the elements 200 to 1000 to the matrix B
C = np.append(B,[200,300,400,500,600,700,800,900,1000])
print(C)

[   1    2    3    4    5    6    7    8    9   10  100  200  300  400
  500  600  700  800  900 1000]


In [102]:
D = np.append(C,np.arange(-100,0,5))
print(D)

[   1    2    3    4    5    6    7    8    9   10  100  200  300  400
  500  600  700  800  900 1000 -100  -95  -90  -85  -80  -75  -70  -65
  -60  -55  -50  -45  -40  -35  -30  -25  -20  -15  -10   -5]


In [104]:
np.append(A,D)

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,    1,
          2,    3,    4,    5,    6,    7,    8,    9,   10,  100,  200,
        300,  400,  500,  600,  700,  800,  900, 1000, -100,  -95,  -90,
        -85,  -80,  -75,  -70,  -65,  -60,  -55,  -50,  -45,  -40,  -35,
        -30,  -25,  -20,  -15,  -10,   -5])

### 10. Different between adjacent elements of array

In [160]:
M = np.arange(0,101,5)
print(M)
print(M.shape)
M1= np.diff(M,n=2)
print(M1)
print(M1.shape)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]
(21,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
(19,)


### 11. Stack of Elements VStack and Column Stack

In [113]:
a =[1,2,3]
b =[4,5,6]
c= [7,8,9]
np.vstack((a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
np.vstack((c,b,a))

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [116]:
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [117]:
np.column_stack((c,b,a))

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

### 12. Array Slicing:Selection of Elements of an array or matrix

In [137]:
R = np.random.rand(3,3)
print(R)

[[0.44575616 0.00364205 0.50510413]
 [0.02693689 0.88620819 0.43478223]
 [0.96445405 0.96681577 0.82833034]]


In [142]:
R[1:3]

array([[0.02693689, 0.88620819, 0.43478223],
       [0.96445405, 0.96681577, 0.82833034]])

In [144]:
R[0:]

array([[0.44575616, 0.00364205, 0.50510413],
       [0.02693689, 0.88620819, 0.43478223],
       [0.96445405, 0.96681577, 0.82833034]])

In [145]:
R[1:2]

array([[0.02693689, 0.88620819, 0.43478223]])

In [149]:
R1 = np.array([1,3,4,5,6,7,8])

In [150]:
R1[3]

5

In [152]:
R1[3:6]

array([5, 6, 7])

### 13. Array Broadcasting

In [154]:
B=np.arange(0,100,5)
print(B)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [155]:
B+5

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [156]:
B-50

array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5,   0,   5,  10,
        15,  20,  25,  30,  35,  40,  45])

In [161]:
B*2

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190])

In [162]:
B/5

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])